--1. number(게시물 순서 seq)
--2. id(아이디)
--3. pwd(비밀번호)
--4. name(이름)
--5. title(제목)
--6. content(내용)
--7. logtime(시간)

--댓글 시퀀스
CREATE SEQUENCE comment_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--유저 테이블
CREATE TABLE UserStatus (
    user_id NUMBER PRIMARY KEY,                  -- userId값
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 가입 시간
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 수정 시간
    is_active NUMBER(1) DEFAULT 0,              -- 온라인 여부
    nickname VARCHAR2(255),                     -- 사용자 이름
    password VARCHAR2(255)                      -- 비밀번호
);

--게시글
CREATE TABLE BoardContents (
    content_id NUMBER PRIMARY KEY,              -- 게시글 ID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 등록 시간
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 수정 시간
    content CLOB,                              -- 게시글 내용
    title VARCHAR2(255),                      -- 게시글 제목
    user_id NUMBER,                           -- 작성자 ID
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES UserStatus(user_id) -- 외래 키 제약 조건
);

--댓글
CREATE TABLE BoardComments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 댓글 ID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,               -- 생성 시간
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         -- 수정 시간
    comment CLOB,                                                 -- 댓글 내용
    content_id NUMBER,                                           -- 게시글 ID
    user_id NUMBER,                                              -- 사용자 ID
    CONSTRAINT fk_content FOREIGN KEY (content_id) REFERENCES BoardContents(content_id), -- 외래 키 제약 조건
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES UserStatus(user_id)                -- 외래 키 제약 조건
);

--댓글 트리거
CREATE OR REPLACE TRIGGER trg_comment_id
BEFORE INSERT ON BoardComments
FOR EACH ROW
BEGIN
    :NEW.comment_id := comment_seq.NEXTVAL;
END;
/
---------------------------------------------------------
select * from UserStatus;
select * from BoardContents;
select * from BoardComments;

commit;

drop table UserStatus purge;
drop table BoardContents purge;
drop table BoardComments purge;
DROP SEQUENCE comment_seq;
------------------------------------------------------------------




--대댓글
create table BoardReplies (
    reply_id bigint primary key auto_increment,   -- replyId
    created_at datetime,                          -- 대댓글 생성 시간
    last_modified_at datetime,                    -- 대댓글 수정 시간
    reply text,                                   -- 대댓글 내용
    comment_id bigint,                            -- 대댓글단 게시글 commentId
    content_id bigint,                            -- 대댓글단 게시글 contentId
    user_id bigint,                               -- 대댓글단 userId
    foreign key (comment_id) references comments(comment_id),
    foreign key (content_id) references contents(content_id),
    foreign key (user_id) references User(user_id)
);
